### PR TITLE
Added Inspiration Section

### PR DESCRIPTION
**Pull request by LanceTurri**
Added inspiration section with useful pattern and interaction libraries as well as a few frameworks I like to use.

### CODE REVIEW

**Comment by jancborchardt** [comment]
@LanceTurri there has been a grammar change by @sohlis just recently so you need to rebase this. Thanks! :)

**Comment by jancborchardt** [comment]
@LanceTurri can you rebase this? Would be cool to get it in. :)

**Comment by simonv3** [comment]
@LanceTurri @jancborchardt I actually came to the resources page looking for inspiration stuff and couldn't find any, so yeah, let's definitely update this!

**Comment by GarthDB** [comment]
feel free to grab the inspiration stuff (and anything else) from [design open](http://designopen.org/resources/)

**Comment by simonv3** [comment]
I'm adding merging this in to my todo list for next week, and adding some of the stuff from design open as well - thanks @GarthDB

**Comment by RichardLitt** [comment]
Yay! Thanks @simonv3 and @LanceTurri

**Pull request merged**
