### PR TITLE
Add research into open source communities

### PR DESCRIPTION
**Pull request by simonv3**

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice, good stuff! Great to get more papers in there.

**Comment by jdittrich** [comment]
Thanks for the papers.
Would be nice though, if future papers would not be behind a login (or do I misunderstand the service?)

**Comment by simonv3** [comment]
You can read them for free without logging in, it's just downloading that
seems to require a log in. I'm not sure why academia does that.

Personally that's a price I'm willing to pay, but maybe that's a standard
(for these resources) we should talk about?

**Comment by jancborchardt** [comment]
Yeah, I tested the links for exactly that reason since I thought they would be behind a log in wall. I could read them online just fine though.

**Comment by jdittrich** [comment]
>You can read them for free without logging in
Great, did not know this.

**Pull request merged**
