### PR TITLE
slight grammar changes

### PR DESCRIPTION
**Pull request by sohlis**

### CODE REVIEW

**Comment by simonv3** [comment]
:+1:

**Comment by simonv3** [comment]
@MorrisJobke why was this deleted?

**Comment by MorrisJobke** [comment]
@simonv3 Because it's merged and the branch isn't needed anymore ;)

**Comment by simonv3** [comment]
@MorrisJobke Yeah, I totally misread the situation (hence the deleted comment). Sorry!

**Comment by MorrisJobke** [comment]
@simonv3 No problem at all :)

**Pull request merged**
