### PR TITLE
Added open source icons project to README.md

### PR DESCRIPTION
**Pull request by adrianmg**
Added to icons resource an open source icons project I'm working on, including SVG & PNG formats.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Great stuff, thank you! :)

**Comment by adrianmg** [comment]
Wow that was fast! :)

**Comment by jancborchardt** [comment]
Yup, someone is always around. :) Great work with the icons – I added you to the Github organization as well.

**Comment by adrianmg** [comment]
Great! Feel free to ask for specific pictograms you may need

**Comment by jancborchardt** [comment]
Yup, someone is always around. :) Great work with the icons – I added you to the Github organization as well.

Also join us in our IRC channel #opensourcedesign (freenode network)

**Pull request merged**
