### PR TITLE
Spelling and punctuation correction

### PR DESCRIPTION
**Pull request by Minimalistic**
"attenion" to "attention", added periods where missing.

### CODE REVIEW

**Comment by simonv3** [comment]
Since these are list items and not full sentences, do they need periods?

**Comment by Minimalistic** [comment]
Can't say I know for certain, maybe you're right.  Though then that means there _were_ some list items with periods and not others - what kind of world twisted would we be living in if we allowed such inconsistencies!

**Comment by PanderMusubi** [comment]
Depends, some lists do not need points, comma's or semicolons. Depends on the language, content adn style you are using.

**Comment by simonv3** [comment]
Grammar amirite? I'm fine with consistency.

**Pull request merged**
