### PR TITLE
Add Tota11y

### PR DESCRIPTION
**Pull request by simonv3**
Tota11y is a bookmarklet that helps you make your website more a11y compliant.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Seems to fit more into the »Learn to code« section. The »other nice stuff« is too general, especially if you add it to the very top of the list.

**Comment by simonv3** [comment]
@jancborchardt Cool, changed. I wasn't sure where to put it, so just plopped it there. Maybe there needs to be a Accessibility section of its own?

**Comment by jancborchardt** [comment]
Yup, when we have more resources then we can just have an own Accessibility section. :)

**Comment by flexbox** [comment]
@jancborchardt Just discovered Tota11y... it's awesome thanks !

**Pull request merged**
