### PR TITLE
Fix Feww speeling mistakes and add on little content

### PR DESCRIPTION
**Pull request by razetime**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Good quote, not sure it is necessary. I don't like making other people feel like idiots.

Maybe just PR the other two line changes?

**Comment by bnvk** [comment]
I agree with @RichardLitt don't really like encouraging people to others feel like idiots, even if it's just being sarcastic or humorous. Not everyone has same sense of humor, thickness of skin, or cultural backgrounds! 

Thanks for the spelling catches :smile:

**Comment by jancborchardt** [comment]
Agree as well on that the quote is not necessary. ;)

**Comment by RichardLitt** [comment]
I do want to point out one thing: thanks so much for this PR! I see it is your first to this repo, and we are super appreciative. 

Let me know if you need help changing the commit, I am more than happy to guide you through that. :)

**Comment by simonv3** [comment]
Awesome, thanks for this @razetime!

**Pull request merged**
