### PR TITLE
Deleted dead links (meaningful transitions, open karma)

### PR DESCRIPTION
**Pull request by jdittrich**
Meaningful transitions is dead; the Open Karma website is broken too; I removed them both for now.

### CODE REVIEW

**Comment by jdittrich** [comment]
»A Beginner’s Guide to Finding User Needs« is a CC-Licenced book written by me – I don’t know how you feel about people adding their projects (even though it is on topic)

**Comment by paulproteus** [comment]
In general I'm +1 on people requesting to add their own projects, if the
community deems the project relevant. I'm curious how others feel.

**Comment by simonv3** [comment]
I'm +1 on it too.

**Comment by jancborchardt** [comment]
@jdittrich thanks for updating, and for adding your book!

Also be welcome in our #opensourcedesign IRC channel :)

**Pull request merged**
