### PR TITLE
 added link to alistapart paperprototyping article. Removed the sentence about paper as (purely) non-interactive.

### PR DESCRIPTION
**Pull request by jdittrich**
I added an article about paper-Prototypes and mockups – it has how-tos and example images, so I suppose it is a good start if one does not know paper mockups/prototypes yet. Since paper prototypes can be used for interactive prototypes too, I removed the sentence saying that paper is non-interactive.

### CODE REVIEW

**Comment by elhombretecla** [comment]
For me it's ok

**Comment by jancborchardt** [comment]
Looks good. Can you squash the commit into one though? :)

**Comment by jdittrich** [comment]
>squash the commit into one though? :)
Sorry, my git magic is not strong enough here. (already pushed, several branches etc.)

**Comment by flexbox** [comment]
### Rebase

* `git log`
  List all your previous commit

* `git rebase -i 4d7ca3bb`
  Select the commit you want to rebase from. Generaly its the commit before your first.

  /!\ `git rebase --abort` Can save your life

      pick bf3e3a2 rename assets
      squash f98622e update page with logo
      squash d3bcb44 update height for navigation menu

  You can found a guide for the keywords [pick, squash, fixup](https://help.github.com/articles/interactive-rebase)

  /!\ When you are on vi mode

  `dd` delete line
  `i` insert a good commit message
  `echap :x` For save the file

* `git push -f` Be careful on this, you tell to the server "You are wrong, i am the boss!"

**Pull request merged**
